# Тема 2.1 Запуск Python. Первая программа

Вопросы:
- Особенности языка программирования Python; 
- Среды программирования.

## Общие сведения о Python 

C историей и общими сведения о языке Python можно ознакомиться [здесь](https://ru.wikipedia.org/wiki/Python).

Дополнительно можно посмотреть: 
1. [Официальный сайт Python](https://www.python.org/).
2. Лутц М. Изучаем Руthon. Том 1. - 5-е изд. - СПб.: ООО "Диалектика", 2019. - 832 с.

## Преимущества Python

- Универсальность;
- Поддержка множества парадигм программирования;
- Кроссплатформенность;
- Свободнораспространяемый и поддерживаемый;
- Прост в реализации и изучении.

## Интерпретатор Python

**Python** — интерпретируемый язык программирования.

Интерпретатор — это программа, которая конвертирует прогрммные инструкции, написанные на Python, в байт-код и выполняет их. Интерпретатор можно рассматривать как программный слой между исходным кодом и железом.

Существует 2 типа интерпретаторов:
- Простой интерпретатор. Он берет одну инструкцию, транслирует и сразу выполняет ее, а затем берет следующую инструкцию;
- Интерпретатор компилирующего типа. Это система из компилятора и интерпретатора. Компилятор переводит исходный код программы в промежуточное представление (байт-код), а интерпретатор (виртуальная машина) выполняет этот байт-код.

Интерпретаторы Python: CPython, Jython, PyPy.

Интерпретатор выполняет любую программу поэтапно:
1. **Инициализация**: после запуска программы Python-интерпретатор читает код, проверяет форматирование и синтаксис.
2. **Компиляция**: интерпретатор переводит исходные инструкции программы в байт-код (низкоуровневое, платформонезависимое представление исходного текста). Такая трансляция необходима в первую очередь для повышения скорости — байт-код выполняется в разы быстрее, чем исходные инструкции.
3. **Выполнение**: скомпилированный байт-код отправляется на виртуальную машину Python (PVM).

Программа на Python --- текстовый файл, содержащий операторы Python.

## Начало работы с Python

- интерактивный режим;
- файлы сценариев.

## Среды разработки

- текстовый редактор;
- [интегрированная среда разработки (IDE)](https://ru.wikipedia.org/wiki/%D0%98%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%B0%D1%8F_%D1%81%D1%80%D0%B5%D0%B4%D0%B0_%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8).


**Интегрированная среда разработки (IDE)** относится к программному приложению, которое предлагает программистам широкие возможности разработки программного обеспечения. IDE чаще всего состоят из редактора исходного кода, средств автоматизации сборки и отладчика.

Возможности IDE, облегчающие разработку:
- подсветка синтаксиса;
- автозаполнение;
- отладка кода.

Примеры IDE:
**IDLE**, **PyCharm**, **Visual Studio Code**, Sublime Text, Vim, Atom, **Spyder**, **Jupyter**. 

Примечание: выделенными редакторами пользовался автор.

# Тема 2.2 Типы данных. Переменные. Инструкции и выражения. Арифметические операторы

## Типы данных

### Типы данных в Python

**Задачи занятия**
- рассмотреть типы данных;
- выбирать тип данных для задания требуемой структуры данных;
- задавать имеющиеся структуры данных, используя типы данных;
- обрабатывать заданные структуры данных.  

Данные в языке `Python` представлены объектами. Каждый объект имеет тип данных и значение.

**Терминология**

Объект в программировании — некоторая сущность в цифровом пространстве, обладающая определённым состоянием и поведением, имеющая определённые свойства (атрибуты) и операции над ними (методы) [[источник](https://ru.wikipedia.org/wiki/%D0%9E%D0%B1%D1%8A%D0%B5%D0%BA%D1%82_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#:~:text=%D0%9E%D0%B1%D1%8A%D0%B5%CC%81%D0%BA%D1%82%20%D0%B2%20%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8%20%E2%80%94%20%D0%BD%D0%B5%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D0%B0%D1%8F%20%D1%81%D1%83%D1%89%D0%BD%D0%BE%D1%81%D1%82%D1%8C,%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B8%20%D0%BD%D0%B0%D0%B4%20%D0%BD%D0%B8%D0%BC%D0%B8%20(%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B).)].

Тип данных (тип) — множество значений и операций над этими значениями [[источник](https://ru.wikipedia.org/wiki/%D0%A2%D0%B8%D0%BF_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85)].

**Типы данных в `Python`**

|Тип|Название|Комментарий|
|--:|:--|:--|
|`int`|Целые числа|Любое целое число без дробной части: `-10`, `1`, `100`, `99999`|
|`float`|Вещественные числа|Любое число с дробной частью (в том числе целое с дробной частью равной `0`): `-10.0`, `1.5`, `100.1`, `99999.0`|
|`bool`|Логический тип данных|Логические переменные могут принимать только два значения -- **True**(истина) или **False**(ложь)|
|`str`|Строки|Любой текст внутри одинарных или двойных кавычек: `'Пример строки с одинарными кавычками'` и `"100.1 - это_строка, а на число"`|
|`list`|Список|Последовательность элементов, разделенных между собой запятой и заключенных в квадратные скобки: `[1,2,'строка', [3,4,{'ключ':'значение'}]]`|
|`dict`|Словарь|Последовательность пар вида `'ключ':'значение'`, заключенная в фигурные скобки `{}`:  `{'Фамилия' : 'Строев', "Имя" : 'Сергей', ('Пол', 'Возраст') : ['М', 40]}`|
|`set`|Множество|Последовательность уникальных элементов, которые разделены между собой запятой и заключены в фигурные скобки `{}`: `{1, 2, 3, 'as'}`|
|`tuple`|Кортеж|Последовательность элементов, которые разделены между собой запятой и заключены в скобки `()`: `(1,2,3, [3,6])`|
|`NoneType`|Неопределенное значение|Объект со значением `None`|

В Python типы данных делятся на **изменяемые** и **неизменяемые**:

- изменяемые: списки (list), множества (set), словари (dict);
- неизменяемые: целые числа (int),  числа с плавающей точкой (float), логические переменные (bool), кортежи (tuple), строки (str).

## Переменные

Для доступа к объекту предназначены **переменные**. Переменная -- это ссылка на объект в памяти компьютера. Иными словами, переменная - это контейнер, которая хранит в себе информацию (текстовую, числовую, какие-то более сложные виды данных).

### Задание переменных

Синтаксис задания 

`имя_переменной` = `значение/тип переменной`

Ограничение на `имя_переменной`:
- чувствительность к регистру;
- состоять из латинских букв, цифр и знаков подчеркивания;
- имя переменной не может начинаться с цифры;
- встроенные идентификаторы / ключевые слова не использовать;
- **не рекомендуется** использовать символа подчеркивания `_` в начале имени переменной.

Список **встроенных идентификаторов** можно получить так
```python
import builtins
print(dir(builtins))
```

Список **ключевых слов** можно получить так
```python
>>> import keyword
>>> keyword.kwlist
```

$\Rightarrow$ Пример задания переменных

In [ ]:
integer_var = 5
float_var = 10.0 
string_var = 'hi'
boolean_var = True
list_var = []
list_var2 = list()

Комментарий: при инициализации переменной `integer_var` на уровне интерпретатора происходит следующее:

- создается целочисленный объект 5 (можно представить, что в этот момент создается ячейка и 5 кладется в эту ячейку);
- данный объект имеет некоторый идентификатор, значение: 5, и тип: целое число;
- посредством оператора `=` создается ссылка между переменной `integer_var` и целочисленным объектом 5 (переменная `integer_var` ссылается на объект 5).

### Проверка типов данных

|Метод|Комментарий|
|--:|:--|
|`type()`|Возвращает тип переменной|

Комментарий: полезные методы

|Метод|Комментарий|
|--:|:--|
|`isalnum()`|Состоит ли строка из букв или цифр|
|`isalpha`|Состоит ли строка из одних букв|
|`isdigit`|Состоит ли строка из одних цифр|

### Преобразование типов данных

|Метод|Комментарий|
|--:|:--|
|`int()`| преобразует аргумент в тип `int`|
|`float()`| преобразует аргумент в тип `float`|
|`bool()`| преобразует аргумент в тип `bool`|
|`list()`| преобразует аргумент в тип `list`|
|`set()`| преобразует аргумент в тип `set`|
|`tuple()`| преобразует аргумент в тип `tuple`|
|`str()`| преобразует аргумент в тип `str`|

## Инструкции и выражения

**Терминология** 

Инструкция в Python — это логическая инструкция, которую интерпретатор Python может прочесть и выполнить. Она может являться выражением или оператором присваивания в Python.

Выражение — один из типов инструкции, который содержит логическую последовательность чисел, строк, объектов и операторов Python.

Операторы позволяют произвести с данными определенные действия.

### Арифметические операторы

Производить операции над числами позволяют математические операторы.

|Оператор|Комментарий|
|--:|:--|
|`+`|сложение|
|`-`|вычитание|
|`*`|умножение|
|`/`|деление. Результатом деления всегда является вещественное число|
|`//`|деление с округлением вниз|
|`%`|остаток от деления|
|`**`|возведение в степень|

Больше арифметических операторов и возможностей в [модуле **math**](https://docs.python.org/3/library/math.html). На русском можно посмотреть [здесь](https://pythonworld.ru/moduli/modul-math.html).

$\Rightarrow$ Пример использования арифметических операторов

In [ ]:
a = 5
b = 10

In [ ]:
print('a+b =', a + b) #Сложение
print('b-a =', b - a) #Вычитание
print('b/a =', b / a) #Деление
print('b*a =', b * a) #Умножение
print('b//a=', b // a) #Целочисленное деление
print('b%3 =', b%3)  #Остаток от деления
print('b**2 =', b ** 2) #Возведение в степень 
print('a**0.5 =', 25 ** 0.5) #Взятие корня

a+b = 15
b-a = 5
b/a = 2.0
b*a = 50
b//a= 2
b%3 = 1
b**2 = 100
a**0.5 = 5.0

### Округление вещественных чисел

У нас часто возникает необходимость превратить вещественное число в целое ("округлить"). В питоне есть несколько способов это сделать, но, к сожалению, ни один из них не работает как наше привычное округление и про это всегда нужно помнить.

Большинство этих функций не реализованы в базовом наборе команд питона и для того, чтобы ими пользоваться, нам придется загрузить дополнительную библиотеку math, которая содержит всякие специальные функции для математических вычислений.

In [ ]:
import math # команда import загружает модуль под названием math

Модуль **math** устанавливается в рамках дистрибутива Anaconda, который мы использовали, чтобы установить Jupyter Notebook, поэтому его не нужно отдельно скачивать, а можно просто импортировать (загрузить в оперативную память текущей сессии). Иногда нужную библиотеку придется сначала установить на компьютер с помощью команды 

```python
!pip install -название модуля- и только потом импортировать.
```

Самый простой способ округлить число - применить к нему функцию int.

In [2]:
int(2.6)

2

Обратите внимание, что такой метод просто обрубает дробную часть (значения выше 0.5 не округляются в сторону большего числа).

In [1]:
print(int(2.6))
print(int(-2.6))

2
-2

Округление "в пол" из модуля math округляет до ближайшего меньшего целого числа.

In [3]:
print(math.floor(2.6)) # чтобы использовать функцю из дополнительного модуля - 
                        # нужно сначала написать название этого модуля и через точку название функции
print(math.floor(-2.6))

NameError: ignored

Округление "в потолок" работает ровно наоброт - округляет до ближайшего большего числа, независимо от значения дробной части.

In [ ]:
print(math.ceil(2.6))
print(math.ceil(-2.6))

3
-2

В самом питоне есть еще функция round(). Вот она работает почти привычно нам, если бы не одно "но"...

In [ ]:
print(round(2.2))
print(round(2.7))
print(round(2.5)) # внимание на эту строку
print(round(3.5))

2
3
2
4

Неожиданно? Тут дело в том, что в питоне реализованы не совсем привычные нам правила округления чисел с вещественной частью 0.5 - такое число округляется до ближайшего четного числа: 2 для 2.5 и 4 для 3.5.

### Другие операторы

**Операторы присваивания**

|Оператор|Комментарий|
|--:|:--|
|`=`|присваивает переменной значение|
|`+=`|увеличивает значение переменной на указанную величину|
|`-=`|уменьшает значение переменной на указанную величину|
|`*=`|умножает значение переменной на указанную величину|
|`/=`|делит значение переменной на указанную величину|
|`//=`| деление с округлением вниз и присваиванием|
|`%=`| деление по модулю и присваивание|
|`**=`| возведение в степень и присваивание|

**Операторы сравнения**

|Оператор|Комментарий|
|--:|:--|
|`==`|равно|
|`!=`|не равно|
|`<`|меньше|
|`>`|больше|
|`<=`|меньше или равно|
|`>=`|больше или равно|
|`in`|проверка на вхождение в последовательность|
|`not in`|проверка на невхождение в последовательность|
|`is`|проверяет, ссылаются ли две переменные на один и тот же объект|
|`is not`|проверяет, ссылаются ли две переменные на разные объекты|

Несколько логических выражений можно объединить в одно большое с помощью следующих операторов.

|Оператор|Комментарий|
|--:|:--|
|`and`|логическое `И`|
|`or`| логическое `ИЛИ`|

**Приоритет операторов сравнения**

1. <, >, <=, >=, ==, !=, <>, is, is not, in, not in.
2. not — логическое отрицание.
3. and — логическое И.
4. or — логическое ИЛИ.

**Операторы для работы с последовательностями**
|Оператор|Комментарий|
|--:|:--|
|`+`|конкатенация|
|`*`|повторение|
|`in`|проверка на вхождение в последовательность|
|`not in`|проверка на невхождение в последовательность|

**Двоичные операторы**

**Приоритет выполнения операторов**

Перечислим операторы в порядке убывания приоритета:
1. $-x$, $+x$, $~x$, $\star \star$ — унарный минус, унарный плюс, двоичная инверсия, возведение в степень. Если унарные операторы расположены слева от оператора $\star \star$, то возведение в степень имеет больший приоритет, а если справа — то меньший. Например, выражение:
$$-10 \star \star -2$$
эквивалентно следующей расстановке скобок:
$$-(10 \star \star (-2));$$
2. *, %, /, // — умножение (повторение), остаток от деления, деление, деление с округлением вниз;
3. $+$, $–$ — сложение (конкатенация), вычитание;
4. <<, >> — двоичные сдвиги;
5. & — двоичное `И`;
6. ^ — двоичное исключающее `ИЛИ`;
7. | — двоичное `ИЛИ`;
8. =, +=, -=, *=, /=, //=, %=, **= — присваивание.

## Работа со строками

### Работа со строками

Строка в Python это:
- последовательность символов, заключенная в кавычки;
- неизменяемый упорядоченный тип данных.

*Сказать*
- операции (+,*);
- индексация (0,-1);
- срезы (срез выполняется по второе число, не включая его; шаг среза);
- организация ввода (input())

Полезные методы работы со строками 

|Метод|Комментарий|
|--:|:--|
|`len()`||
|`.join()`||
|`.replace`||
|`.split()`||
|`.strip()`||
|`.upper(), .lower(), .swapcase(), .capitalize()`||
|`.find()`||
|`.count`||

### Форматирование строк (string formatting)
Напишем программу, которая выводит на экран введенные данные, чтобы пользователь мог их проверить.

Пусть для начала пользователь вводит свое имя и возраст.

In [ ]:
name = input("Введите Ваше имя: ")
age = int(input("Введите Ваш возраст: ")) # возраст будет целочисленным

Введите Ваше имя: Сергей
Введите Ваш возраст: 40

Теперь выведем на экран сообщение вида

`Ваше имя: `имя`. Ваш возраст: `возраст`.`

Но прежде, чем это сделать, поймем, какого типа будут значения, которые мы будем подставлять в шаблон. Имя (переменная name) – это строка (string), а возраст (переменная age) – это целое число (integer).

In [ ]:
result = "Ваше имя: %s. Ваш возраст: %i." % (name, age)
print(result)

Ваше имя: Сергей. Ваш возраст: 40.

Что за таинственные %s и %i? Все просто: оператор % в строке указывает место, на которое будет подставляться значение, а буква сразу после процента – сокращённое название типа данных (s – от string и i – от integer). Осталось только сообщить Python, что именно нужно подставлять – после кавычек поставить % и в скобках перечислить названия переменных, значения которых мы будем подставлять.

In [ ]:
print("Ваше имя: %s. Ваш возраст: %i.")

Ваше имя: %s. Ваш возраст: %i.

Важно помнить, что если мы забудем указать какую-то из переменных, мы получим ошибку (точнее, исключение): Python не будет знать, откуда брать нужные значения.

In [ ]:
print("Ваше имя: %s. Ваш возраст: %i." % (name))

TypeError: ignored

Кроме того, создавая такие текстовые шаблоны, нужно обращать внимание на типы переменных, значения которых мы подставляем.

In [ ]:
print("Ваше имя: %s. Ваш возраст: %s." % (name, age)) # так сработает

Ваше имя: Сергей. Ваш возраст: 40.

In [ ]:
print("Ваше имя: %i. Ваш возраст: %s." % (name, age)) # а так нет

TypeError: ignored

В первом случае код сработал: Python не очень строго относится к типам данных, и поэтому он легко может превратить целочисленный возраст в строку (два %s вместо %s и %i не является помехой). Во втором случае все иначе. Превратить строку, которая состоит из букв (name) в целое число никак не получится, поэтому Python справедливо ругается.

А что будет, если мы будем подставлять не целое число, а дробное, с плавающей точкой? Попробуем!

In [ ]:
height = float(input("Введите Ваш рост (в метрах): "))
height

Введите Ваш рост (в метрах): 1.78

1.78

In [ ]:
print("Ваш рост: %f м." % height) # f - от float

Ваш рост: 1.780000 м.

По умолчанию при подстановке значений типа float Python выводит число с шестью знаками после запятой. Но это можно исправить. Перед f нужно поставить точку и указать число знаков после запятой, которое мы хотим:

In [ ]:
print("Ваш рост: %.2f м." % height) # например, два

Ваш рост: 1.78 м.

In [ ]:
print("Ваш рост: %.1f м. " % height) # или один

Ваш рост: 1.8 м.

В случае, если указанное число знаков после запятой меньше, чем есть на самом деле (как в ячейке выше), происходит обычное арифметическое округление.

Рассмотренный выше способ форматирования строк – не единственный. Он довольно стандартный, но при этом немного устаревший. В Python 3 есть другой способ ‒ форматирование с помощью метода .format(). Кроме того, в Python 3.6 и более поздних версиях появился еще более продвинутый способ форматирования строк ‒ f-strings (formatted string literals).

F-strings очень удобны и просты в использовании: вместо % и сокращённого названия типа в фигурных скобках внутри текстового шаблона нужно указать название переменной, из которой должно подставляться значение, а перед всей строкой добавить f, чтобы Python знал, что нам нужна именно f-string.

In [ ]:
print(f"Ваше имя: {name}. Ваш возраст: {age}. Рост: {height:.2f}")

Ваше имя: Сергей. Ваш возраст: 40. Рост: 1.78

Альтерантивой такого кода будет следующий синтаксис. Здесь переменные вставятся в порядке "упоминания" в строке.

In [ ]:
print("Ваше имя: {}. Ваш возраст: {}".format(name, age))

Ваше имя: Сергей. Ваш возраст: 40

Форматирование дробей добавляем так.

In [ ]:
print("Ваше имя: {}. Ваш возраст: {}. Рост: {:.2f}".format(name, age, height))

Ваше имя: Сергей. Ваш возраст: 40. Рост: 1.78

Если указали формат переменной (.2f, например, ожидает float), то следим за порядком.

In [ ]:
print("Ваше имя: {}. Ваш возраст: {}. Рост: {:.2f}".format(age, height, name))

ValueError: ignored

Порядок заполнения можно указывать с помощью нумерации. Одну и тоже переменную можно использовать несколько раз.

In [ ]:
print("Ваше имя: {2}. Ваш возраст: {0}. Рост: {1:.2f}. Все верно, {2}?".format(age, height, name))

Ваше имя: Сергей. Ваш возраст: 40. Рост: 1.78. Все верно, Сергей?

## Работа со списком

### Работа со списком

Список в Python это:
- последовательность элементов, разделенных между собой запятой и заключенных в квадратные скобки;
- изменяемый упорядоченный тип данных.

Сказать:
- задание списка;
- индексация (можно изменять), срезы.

Полезные методы работы со списками

|Метод|Комментарий|
|--:|:--|
|`len()`||
|`.append()`||
|`.pop(индекс)`||
|`.remove(элемент)`||
|`.()`||
|`.upper(), .lower(), .swapcase(), .capitalize()`||
|`.find()`||
|`.count`||

In [ ]:
students = [1, 2, 3, 3, 4, 
             5, 66, 
             7, 7]
print(students)
print(type(students))

[1, 2, 3, 3, 4, 5, 66, 7, 7]
<class 'list'>

In [ ]:
students.append('понедельник')
students

['привет', 2, 3, 3, 4, 5, 66, 7, 7, 'список', 'список', 'понедельник']

In [ ]:
lst_number = [1, 2, 3, 4, 1, 0]
lst_new = list()
lst_new.append(lst_number[0])
lst_new.append(lst_number[1])
lst_new.append(lst_number[4])
lst_new.append(lst_number[5])

lst_new

[1, 2, 1, 0]

In [ ]:
#lst_new = list()
for i in lst_number:
    if i < 3:
        lst_new.append(i)
lst_new

[1, 2, 1, 0, 1, 2, 1, 0]

Пустой список можно создать двумя способами - оператором [] и функцией list().

In [ ]:
print([])
print(list())

[]
[]

In [ ]:
a = list()
a

[]

Список может содержать любые данные - например, числа.  
Давайте создадим список оценок студента.

In [ ]:
notes = [6, 5, 7, 5, 8]
print(notes)

[6, 5, 7, 5, 8]

Список может быть даже смешанным. Например, давайте сохраним в одном списке имя студента, его год рождения, средний балл, и логическую переменную, которая будет равна True, если студент учится на бюджете.

In [ ]:
student1 = ['Ivan Ivanov', 1987, 7.5, True]
print(student1)

['Ivan Ivanov', 1987, 7.5, True]

Список может даже содержать другие списки.  
Давайте создадим еще одного студента по аналогии со student1 и положим этих двух студентов в еще один список.

In [ ]:
student2 = ['Maria Smirnova', 1991, 7.9, False]
students = [student1, student2]
print(students)

[['Ivan Ivanov', 1987, 7.5, True], ['Maria Smirnova', 1991, 7.9, False]]

Элементы списков нумеруются, начиная с 0. Мы можем получить доступ к элементу списка по его индексу.

In [ ]:
students = ['Ivan Ivanov', 'Tatiana Sidorova', 'Maria Smirnova']
print(students[0]) # первый элемент
print(students[1]) # второй элемент
print(students[-2]) # последний элемент

Ivan Ivanov
Tatiana Sidorova
Tatiana Sidorova

Ксати, индексация работает и в строках. Там отдельными элементами являются символы.

In [ ]:
x = 'слово'
print(x[0])
print(x[-1])

с
о

Мы можем узнать длину списка с помощью функции len() (работает и для строк).

In [ ]:
print(len(students)) # количество элементов в списке students
print(len(x)) # количество символов в строке x

3
5

Но, в отличие от строк, список можно изменить.

In [ ]:
students = ['Ivan Ivanov', 'Tatiana Sidorova', 'Maria Smirnova']
students

['Ivan Ivanov', 'Tatiana Sidorova', 'Maria Smirnova']

In [ ]:
students[0] = 'Sergey Stroev'
students

['Sergey Stroev', 'Tatiana Sidorova', 'Maria Smirnova']

In [ ]:
string = 'ololololol'
string[1] = 'a'

TypeError: ignored

Строки - неизменяемый тип данных, поэтому присвоение символа по индексу не сработает.

Еще одна операция, которая работает со всеми последовательностями - проверка на наличие элемента in и not in. Возвращает True или False.

In [ ]:
### students = ['Ivan Ivanov', 'Tatiana Sidorova', 'Maria Smirnova']
# print('Ivan Ivanov' in students)

n = [1,2,3,4]
x = 500
x not in n
# print('Petr' not in students[2])
# print(2 in students)

True

Способ расширить список - метод .append(), который добавляет аргумент в список в качестве последнего элемента.

In [ ]:
lst = [0, 1, 2, 3, 4, 'cat', 'dog','cat']

lst.append(5)
print(lst)


lst += [6] # эквивалентное append выражение
print(lst)

[0, 1, 2, 3, 4, 'cat', 'dog', 'cat', 5]
[0, 1, 2, 3, 4, 'cat', 'dog', 'cat', 5, 6]

Удалить элемент из списка можно с помощью метода .remove() (без возвращения удаленного элемента) или .pop (с возвращением удаленного элемента).

In [ ]:
lst.remove('cat') # аргумент - объект, который ходим удалить
print(lst)

[0, 1, 2, 3, 4, 'dog', 'cat', 5, 6]

In [ ]:
x = lst.pop(0) # аргумент - индекс объекта. Результат операции можно сохранить в переменную
print(lst)
print(x)

[1, 2, 3, 4, 'dog', 'cat', 5]
0

Поиском в списках занимается метод .index(), который вернет индекс объекта, переданного в качестве аргумента.

In [ ]:
lst.append('dog')

In [ ]:
lst

[1, 2, 3, 4, 'dog', 'cat', 5, 'dog']

In [ ]:
print(lst.index('dog'))

4

In [ ]:
print(lst.count('dog'))

2

In [ ]:
# находим индекс объекта 'dog'
print(lst[lst.index('dog')]) # используем метод, возвращающий индекс, для обращения к объекту

5
dog

Если говорить еще о полезных методах, то это .count(), который подсчитывает количество элементов и .reverse(), который разворачивает список. Ниже еще отдельно поговорим о сортировке.

In [ ]:
b = [1,2,3,4,5]
b.reverse()
b

[5, 4, 3, 2, 1]

In [ ]:
 # считаем количество 'dog' в списке
lst.reverse() # разворачиваем список. Осторожно - метод меняет список!
print(lst)

1
[5, 'dog', 4, 3, 2, 1, 0]

Все методы списков [здесь](https://docs.python.org/3/tutorial/datastructures.html)

In [ ]:
lst_new

[1, 2, 1, 0, 1, 2, 1, 0]

In [ ]:
lst_new[:5:3]

[1, 0]

#### Сортировки

Отдельно следует рассказать про метод **sort()**. Метод производит сортировку списка.
Задачи сортировки - очень распространены в программировании. 
В общем случае, они сводятся к выстроению элементов списка в заданном порядке.
В Python есть встроенные методы для сортировки объектов для того, чтобы программист 
мог не усложнять себе задачу написанием алгоритма сортировки. 
Метод **list.sort()** - как раз, один из таких случаев.

In [ ]:
test_list = [5, 8, 1, 4, 3, 7, 2]
print(test_list)  # Элементы списка расположены в хаотичном порядке
test_list.sort()
print(test_list)  # Теперь элементы списка теперь расположены по возрастанию

[5, 8, 1, 4, 3, 7, 2]
[1, 2, 3, 4, 5, 7, 8]

In [ ]:
test_list.sort(reverse = True)

In [ ]:
test_list

[8, 7, 5, 4, 3, 2, 1]

Таким образом, метод **list.sort()** упорядочил элементы списка test_list
Если нужно отсортировать элементы в обратном порядке, то можно использовать именнованный параметр reverse.

In [ ]:
test_list.sort(reverse=True)  # параметр reverse указывает на то, что нужно отсортировать список в обратном порядке
print(test_list)

[8, 7, 5, 4, 3, 2, 1]

Следует обратить внимание, что метод **list.sort()** изменяет сам список, на котором его вызвали. 
Таким образом, при каждом вызове метода "**sort()**", наш список "test_list" изменяется. 
Это может быть удобно, если нам не нужно держать в памяти исходный список. 
Однако, в противном случае, или же - в случае неизменяемого типа данных (например, кортежа или строки) - 
этот метод не сработает. В таком случае, на помощь приходит встроенная в питон функция **sorted()**

In [ ]:
print(sorted(test_list))  # Сам список при сортировке не изменяется

[1, 2, 3, 4, 5, 7, 8]

In [ ]:
test_list

[8, 7, 5, 4, 3, 2, 1]

Так как sorted() функция, а не метод, то будет работать и с другими типами данных.

In [ ]:
print(sorted('something'))

['e', 'g', 'h', 'i', 'm', 'n', 'o', 's', 't']

In [ ]:
# print(sorted('something')) отсортирует буквы в строке, но выведет список
print(''.join(sorted('something'))) # с помощью метода join можно собрать отсортированную строку, чуть ниже подробнее про него

eghimnost

У функции sorted(), как и у метода list.sort() есть параметр key, 
с помощью которого можно указать функцию, которая будет применена к каждому элементу 
последовательности при сортировке.

In [ ]:
test_string = 'A string With upper AND lower cases'

In [ ]:
print(sorted(test_string.split())) # заглавные буквы получили приоритет над строчными

['A', 'AND', 'With', 'cases', 'lower', 'string', 'upper']

In [ ]:
print(sorted(test_string.split(), key=str.upper)) # все буквы были приведены к верхнему регистру, сортировка получилась по алфавиту

['A', 'AND', 'cases', 'lower', 'string', 'upper', 'With']

#### Функция map()

Функция map() берет функцию и последовательность и применяет эту функцию ко всем ее элементам (map() всегда будет ожидать от вас два аргумента).

Обратите внимание, чтобы увидеть результат работы этой функции надо дополнительно вручную преобразовать в список (или в кортеж, в зависимости от ваших целей).

In [ ]:
print(map(bool, [9, 0, 8, -288, 998, 0])) # не совсем то, что надо
print(list(map(bool, [9, None, 8, -288, 998, 0]))) # а теперь работает, каждое число преобразовалось в логическую переменную

<map object at 0x1090f5290>
[True, False, True, True, True, False]

#### Ввод и вывод списков

Теперь мы можем быстро вводить и выводить списки, содержащие разные данные через разные разделители.

In [ ]:
print('-'.join(list(map(int,input().split()))))

1 2 3 4

TypeError: sequence item 0: expected str instance, int found

In [ ]:
phone = list(map(int, input().split())) # получаем строку, разбиваем по пробелу, сразу преобразуем все элементы в числа
print(phone)
print('-'.join(list(map(str, phone)))) # преобразуем массив чисел в массив строк и склеиваем через дефис

[8, 913, 899, 99, 99]
8-913-899-99-99

Также, если нет задачи сохранить результат в переменную в виде строки, вместо join() можно использовать распаковку. 
Мы ставим оператор * перед списком, и, например, функция print() будет воспринимать его не как список, а как последовательность объектов.

In [ ]:
print(phone, sep='-') # не работает, получили список
print(*phone, sep='-') # теперь сработало. По сути, распакованный список питон видит как в примере ниже
print(phone[0], phone[1], phone[2], phone[3], phone[4], sep='-')

[8, 913, 899, 99, 99]
8-913-899-99-99
8-913-899-99-99

## Работа со словарем

### Работа со словарем

Словарь состоит из набора ключей и соответствующих им значений. Значения могут быть любыми объектами (также как и в списке, хранить можно произвольные объекты). А ключи могут быть почти любыми объектами, но только неизменяемыми. В частности числами, строками, кортежами. Список или множество не могут быть ключом.

Одному ключу соответствует ровно одно значение. Но одно и то же значение, в принципе, можно сопоставить разным ключам.

In [ ]:
dict_example = {
    'name' : 'Сергей',
    1 : [1,2,3,'Привет']
    }

In [ ]:
dict_example['2'] = 'нет спешки'
dict_example

{1: [1, 2, 3, 'Привет'], '2': 'нет спешки', 'name': 'Сергей'}

In [ ]:
a = dict()
type(a)

dict

In [ ]:
a['chapter1'] = 'ghfdlksgrjkasgdjkagrdjksargs'
a

{'chapter1': 'ghfdlksgrjkasgdjkagrdjksargs'}

In [ ]:
a[1] = 'hrjegrejk'
a

{1: 'hrjegrejk', 'chapter1': 'ghfdlksgrjkasgdjkagrdjksargs'}

In [ ]:
x = (3,4,5)
a[x] = 'hrjekwslerw'
a

{(3, 4, 5): 'hrjekwslerw',
 1: 'hrjegrejk',
 'chapter1': 'ghfdlksgrjkasgdjkagrdjksargs'}

In [ ]:
x = (1,2,3,'str')
a[x] = 'fuidaslt'

In [ ]:
a

{'chapter1': 'ghfdlksgrjkasgdjkagrdjksargs',
 1: 'hrjegrejk',
 (3, 4, 5): 'hrjekwslerw',
 (1, 2, 3, 'str'): 'fuidaslt'}

In [ ]:
a = dict()
a[(2,3)] = [2,3] # кортеж может быть ключом, потому что он неизменямый
a

{(2, 3): [2, 3]}

In [ ]:
b = dict()
b[[2,3]] = [2,3] # а список уже нет, получим ошибку
print(b)

TypeError: unhashable type: 'list'

#### Создание словаря
В фигурных скобках через двоеточие ключ:значение

In [ ]:
d = dict()
d

{}

In [ ]:
d1 = {"кот": 10, "и": 100, "Тейлора": 2}
print(d1)

{'кот': 10, 'и': 100, 'Тейлора': 2}

In [ ]:
d1["кот"]

10

Через функцию dict(). Обратите внимание, что тогда ключ-значение задаются не через двоеточие, а через знак присваивания. А строковые ключи пишем без кавычек - по сути мы создаем переменные с такими названиями и присваиваим им значения (а потом функция dict() уже превратит их в строки).

In [ ]:
d2 = dict(кот=10, и=100, Тейлора=2)
print(d2) # получили тот же результат, что выше

{'кот': 10, 'и': 100, 'Тейлора': 2}

И третий способ - передаем функции dict() список списков или кортежей с парами ключ-значение.

In [ ]:
d3 = dict([("кот", 10), ("и", 100), ("Тейлора", 2)]) # перечисление (например, список) tuple
print(d3)

{'кот': 10, 'и': 100, 'Тейлора': 2}

Помните, когда мы говорили про списки, мы обсуждали проблему того, что важно создавать именно копию объекта, чтобы сохранять исходный список. Копию словаря можно сделать так

In [ ]:
d4 = dict(d3) # фактически, копируем dict который строчкой выше
print(d4)

{'кот': 10, 'и': 100, 'Тейлора': 2}

In [ ]:
d1 == d2 == d3 == d4 # Содержание всех словарей одинаковое

True

Пустой словарь можно создать двумя способами.

In [ ]:
d2 = {} # это пустой словарь (но не пустое множество)
d4 = dict()
print(d2, d4)

{} {}

In [ ]:
x = {}
type(x)

dict

#### Операции со словарями

Как мы уже говорили, словари неупорядоченные структуры и обратиться по индексу к объекту уже больше не удастся.

In [ ]:
d1[1] # выдаст ошибку во всех случах кроме того, если в вашем словаре вдруг есть ключ 1

KeyError: 1

Но можно обращаться к значению по ключу.

In [ ]:
d3 = dict([("кот", 10), ("и", 100), ("Тейлора", 2)])
print(d1['кот'])

10

In [ ]:
d1[1]

KeyError: 1

Можно создать новую пару ключ-значение. Для этого просто указываем в квадратных скобках название нового ключа.

In [ ]:
d1[1] = 'test'
print(d1[1]) # теперь работает!

test

Внимание: если элемент с указанным ключом уже существует, новый с таким же ключом не добавится! Ключ – это уникальный идентификатор элемента. Если мы добавим в словарь новый элемент с уже существующим ключом, мы просто изменим старый – словари являются изменяемыми объектами.

In [ ]:
d3 = dict([("кот", 10), ("и", 100), ("Тейлора", 2)])
d1["кот"] = 11 # так же как в списке по индексу - можно присвоить новое значение по ключу
d1

{'Тейлора': 2, 'и': 100, 'кот': 11}

In [ ]:
d1["кот"] += 1 # или даже изменить его за счет арифметической операции
d1

{'Тейлора': 2, 'и': 100, 'кот': 12}

А вот одинаковые значения в словаре могут быть.

In [ ]:
d1['собака'] = 12
print(d1)

{'кот': 12, 'и': 100, 'Тейлора': 2, 'собака': 12}

Кроме обращения по ключу, можно достать значение с помощью метода .get(). Отличие работы метода в том, что если ключа еще нет в словаре, он не генерирует ошибку, а возвращает объект типа None ("ничего"). Это очень полезно в решении некоторых задач.

In [ ]:
d1

{'кот': 13, 'и': 100, 'Тейлора': 2, 1: 'test', 'собака': 13}

In [ ]:
print(d1['кот'])

In [ ]:
print(d1.get("ктоо")) # вернут None

None

Удобство метода .get() заключается в том, что мы сами можем установить, какое значение будет возвращено, в случае, если пары с выбранным ключом нет в словаре. Так, вместо None мы можем вернуть строку Not found, и ломаться ничего не будет:

In [ ]:
print(d1.get("ктоо", 'Not found')) # передаем вторым аргументом, что возвращать
print(d1.get("ктоо", False)) # передаем вторым аргументом, что возвращать

Not found
False

Также со словарями работают уже знакомые нам операции - проверка количества элементов, проверка на наличие объектов.

In [ ]:
d1

In [ ]:
print(d1)
print("кот" in d1) # проверка на наличие ключа
print("ктоо" not in d1) # проверка на отстуствие ключа

{'кот': 13, 'и': 100, 'Тейлора': 2, 1: 'test', 'собака': 13}
True
True

Удалить отдельный ключ или же очистить весь словарь можно специальными операциями.

In [ ]:
del d1["кот"]

In [ ]:
d1

{'и': 100, 'Тейлора': 2, 1: 'test', 'собака': 13}

In [ ]:
d1.clear()
d1

{}

In [ ]:
del d1["кот"] # удалить ключ со своим значением
print(d1)
d1.clear() # удалить все
print(d1)

{'и': 100, 'Тейлора': 2, 1: 'test'}
{}

In [ ]:
d1 = dict([("кот", 10), ("и", 10), ("Тейлора", 2)])

У словарей есть три метода, с помощью которых мы можем сгенерировать список только ключей, только значений и список пар ключ-значения (на самом деле там несколько другая структура, но ведет себя она очень похоже на список).

In [ ]:
print(d1.values()) # только значения
print(d1.keys()) # только ключи
print(d1.items()) # только ключ-значение

dict_values([10, 10, 2])
dict_keys(['кот', 'и', 'Тейлора'])
dict_items([('кот', 10), ('и', 10), ('Тейлора', 2)])

Ну, и раз уж питоновские словари так похожи на обычные, давайте представим, что у нас есть словарь, где все слова многозначные. Ключом будет слово, а значением ‒ целый список.

In [ ]:
my_dict = {'swear' : {'swear' : ['клясться', 'ругаться'], 'dream' : ['спать', 'мечтать']}, 'dream' : ['спать', 'мечтать']}

По ключу мы получим значение в виде списка:

In [ ]:
my_dict['swear']['swear'][0]

'клясться'

Так как значением является список, можем отдельно обращаться к его элементам:

In [ ]:
my_dict['swear'][0] # первый элемент

'клясться'

Можем пойти дальше и создать словарь, где значениями являются словари! Например, представим, что в некотором сообществе проходят выборы, и каждый участник может проголосовать за любое число кандидатов. Данные сохраняются в виде словаря, где ключами являются имена пользователей, а значениями – пары *кандидат-голос*.

In [ ]:
votes = {'user1': {'cand1': '+', 'cand2': '-'},
         'user2' : {'cand1': 0, 'cand3' : '+'}} # '+' - за, '-' - против, 0 - воздержался

In [ ]:
votes

{'user1': {'cand1': '+', 'cand2': '-'}, 'user2': {'cand1': 0, 'cand3': '+'}}

По аналогии с вложенными списками по ключам мы сможем обратиться к значению в словаре, который сам является значением в `votes` (да, эту фразу нужно осмыслить):

In [ ]:
votes['user1']['cand1'] # берем значение, соответствующее ключу user1, в нем – ключу cand1

'+'

In [ ]:
dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}
dict3 = dict1.copy()
dict3.update(dict2)
print(dict3)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [ ]:
dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}
dict3 = {**dict1, **dict2}
print(dict3)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

Через занятие мы с вами начнем работать с условными операторами и циклом for, и тогда мы поговорим об особенностях обращения к значениям в цикле и сортировок словарей.

In [ ]:
arters = {
    "Т. Круз" : ['Миссия невыполнима 1', 'Миссия невыполнима 2',  'Миссия невыполнима 4'],
    "В. Машков" : ['Идиот',  'Миссия невыполнима 4']
}

In [ ]:
len(arters["Т. Круз"])

3

In [ ]:
len(arters["В. Машков"])

2

In [ ]:
arters.keys()

dict_keys(['Т. Круз', 'В. Машков'])

In [ ]:
arters.values()

dict_values([['Миссия невыполнима 1', 'Миссия невыполнима 2', 'Миссия невыполнима 4'], ['Идиот', 'Миссия невыполнима 4']])

In [ ]:
lst_new = list()
for i in arters.keys():
    print(arters[i])
    lst_new.append(len(arters[i]))

['Миссия невыполнима 1', 'Миссия невыполнима 2', 'Миссия невыполнима 4']
['Идиот', 'Миссия невыполнима 4']

In [ ]:
dict_temp = dict(zip(lst_new, arters.keys())) 
dict_temp

{2: 'В. Машков', 3: 'Т. Круз'}

In [ ]:
a = sorted(lst_new, reverse = True)
dict_temp[a[0]]

'Т. Круз'

In [ ]:
for i in a:
    print(dict_temp[i])

Т. Круз
В. Машков

In [ ]:
()lst_new

[3, 2]

## Работа с множеством

In [ ]:
x = set()
type(x)

set

In [ ]:
x = (4, 5, 6)
print(set(x)) # передаем список

{4, 5, 6}

In [ ]:
set(range(10))

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [ ]:
print(set()) # передаем tuple
print(set(range(10)))
print(set()) # пустое множество

set()
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
set()


Другой способ создать множество - это перечислить его элементы в фигурных скобках (список - в квадратных, кортеж в круглых, а множество - в фигурных)

In [ ]:
primes = {2, 3, 5, 7}
animals = {"cat", "dog", "horse", 'cat'}

print(primes)
print(animals)

{2, 3, 5, 7}
{'cat', 'horse', 'dog'}

In [ ]:
x = [1,2,3,2,2,2,2,2,2,2,'dog',1]
print(set(x))

{1, 2, 3, 'dog'}

Кстати, обратите внимание, что множество может состоять только из уникальных объектов. Выше множество animals включает в себя только одну кошку несмотря на то, что в конструктор мы передали 'cat' два раза. Преобразовать в список в множество - самый простой способ узнать количество уникальных объектов.

Со множествами работает почти всё, что работает с последовательностями (но не работают индексы, потому что элементы не хранятся упорядоченно).

In [ ]:
print(len(primes))

4

In [ ]:
primes = {1,11,22,34,5}
11 in primes

True

In [ ]:
animals = {"cat", "dog", "horse", 'cat'}
"cow" in animals

False

In [ ]:
 # длина
print(11 in primes) # проверка на наличие элемента in хорошо и быстро работает для множеств
print("cow" in animals)

True
False

Все возможные операции с множествами: https://docs.python.org/3/library/stdtypes.html#set-types-set-frozenset

Отдельно мы посмотрим на так называемые операции над множествами. Если вы знаете круги Эйлера, то помните как различают объекты множеств - пересечение, объекты, которые принадлежат множеству а, но не принадлежат b и так далее. Давайте посмотрим, как эти операции реализовани в питоне.

In [ ]:
a = {1, 2, 3, 4}
b = {3, 4, 5, 6}
c = {2, 3}

In [ ]:
print(c <= a)

True

In [ ]:
print(c >= a)

False

In [ ]:
print(a | b)

{1, 2, 3, 4, 5, 6}

In [ ]:
a.intersection(b)

{3, 4}

In [ ]:
a.union(b)

{1, 2, 3, 4, 5, 6}

In [ ]:
a^b

{1, 2, 5, 6}

In [ ]:
b.difference(a)

{5, 6}

In [ ]:
a = {1, 2, 3, 4}
b = {3, 4, 5, 6}
c = {2, 3}

 # проверка на подмножество (с подномжество a)
print(c <= b) # не подмножество, т.к. в b нет 2 
print(a >= c) 
print(a | b) # объединение a.union(b) aka a+b
print(a & b) # пересечение a.intersection(b)
print(a - b) # разность множеств (все что в a, кроме b) a.difference(b)
print(a ^ b) # симметрическая разность множеств (объединение без пересечения) 

c = a.copy() # копирование множества, или set(a)
print(c)

True
False
True
{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5, 6}
{3, 4}
{1, 2}
{1, 2, 5, 6}
{1, 2, 3, 4}

In [ ]:
a = {1, 2, 3, 4}
c = a.copy()
c

{1, 2, 3, 4}

In [ ]:
print(c.issubset(a)) # c <= a 
print(c.isdisjoint(a)) # a и c не пересекаются?
print(a.issuperset(c)) # a включает в себя с как подмножество

True
False
True

In [ ]:
s = {1,2,3}
s

{1, 2, 3}

In [ ]:
s.add(10)
s

{1, 2, 3, 10}

In [ ]:
s.add(10)
s

{1, 2, 3, 10}

In [ ]:
s.discard(500)
s

{1, 2, 3, 10}

In [ ]:
x = s.pop()
print(s)
print(x)

{1, 2, 3}
10

In [ ]:
s

{1, 2, 3}

In [ ]:
s.clear()
s

set()

Предыдущие операции не меняли множества, создавали новые. А как менять множество:

In [ ]:
s = {1, 2, 3}
s.add(10) # добавить
print(s) # обратите внимание, что порядок элементов непредсказуем
s.remove(1) # удаление элемента
s.discard(1) # аналогично, но не будет ошибки, если вдруг такого элемента нет в множестве
print(s)
x = s.pop() # удаляет и возвращает один произвольный элемент множества (можем сохранить его в переменную)
print(s)
print(x)
s.clear() # очистить
print(s)

{10, 1, 2, 3}
{10, 2, 3}
{2, 3}
10
set()

In [ ]:
x = 1
x +=1 
x

2

In [ ]:
s = {1,2}
# s |= {10, 20}
s = s|{10, 20}
s

{1, 2, 10, 20}

Как мы сокращали арифметические операции раньше (например, +=), так же можно сокращать операции над множествами.

In [ ]:
s |= {10, 20} # s = s | {10, 20} # объединение множества s с {10,20}
print(s)
# s ^=, s &= и т.п.

{10, 20}

## Работа с кортежем

### Работа с кортежем

Кортежи очень похожи на списки.

In [ ]:
student = ('Ivan Ivanov', 2001, 7.5, True)
print(student)
print(type(student))

('Ivan Ivanov', 2001, 7.5, True)
<class 'tuple'>

Пустой кортеж можно создать с помощью оператора () либо функции tuple.

In [ ]:
print(())
print(tuple())

()
()

In [ ]:
x = tuple()
x

()

In [ ]:
student

('Ivan Ivanov', 2001, 7.5, True)

Основное отличие кортежей от списков состоит в том, что кортежи нельзя изменять (да-да, прямо как строки).

In [ ]:
student[1] = 2002

TypeError: 'tuple' object does not support item assignment

Списки и кортежи могут быть вложены друг в друга.  
Например, пусть в информации о студенте у нас будет храниться не его средний балл, а список всех его оценок.

In [ ]:
student = ('Ivan Ivanov', 2001, [8, 7, 7, 9, 6], True)
print(student)

('Ivan Ivanov', 2001, [8, 7, 7, 9, 6], True)

In [ ]:
student = ('Ivan Ivanov', 2001, (8, 7, 7, 9, 6), True)
print(student)

('Ivan Ivanov', 2001, (8, 7, 7, 9, 6), True)

Мы можем обратиться к элементу вложенного списка или кортежа с помощью двойной индексации.

In [ ]:
print(student[2][1]) # получили вторую оценку

7

Иногда бывает полезно обезопасить себя от изменений массивов данных и использовать кортежи, но чаще всего мы все-таки будем работать со списками.